### ISSUE TITLE
Not detecting people que

### ISSUE THREAD

**Issue by Nauchism** [RXJpaw/Valorant-Companion#11]
I don't think The tracking for parties is working ^^

**Comment by RXJpaw** [comment]
Yea ... Valorant removed the API for that long time ago, sorry. :/

**Comment by Nauchism** [comment]
> Yea ... Valorant removed the API for that long time ago, sorry. :/

How does tracker.gg still manage to track parties?

**Comment by RXJpaw** [comment]
Tracker Network is allowed to use parts of Riot's official API to retrieve such data.
But I'm limited to Valorant's in-game API, which doesn't allow party exposure anymore.
