### ISSUE TITLE
About update.bin file

### ISSUE THREAD

**Issue by Bamboozul** [RXJpaw/Valorant-Companion#3]
How do I use the update.bin file to update without rebuilding the whole project?

**Comment by RXJpaw** [comment]
The `update.bin` is not a file used manually but a file that is used to auto-update the Valorant Companion.
Click the highlighted button to use the auto-update feature. If it says "External Update" you have to download and use the installer again.
![image](https://github.com/RXJpaw/Valorant-Companion/assets/45784529/1a06f213-cafe-481d-98f3-7e6a00a2ea35)
