### ISSUE TITLE
Agent lock functionality?

### ISSUE THREAD

**Issue by NoozAbooz** [RXJpaw/Valorant-Companion#5]
Would it be possible to use the API to add the ability to lock agents, similiar to Recon Bolt? Just curious.

**Comment by RXJpaw** [comment]
Hey!

Yes. Valorant provides an API for selecting and then locking agents early.
This isn't a feature implemented into Valorant Companion for two reasons;

* Agent-locking is a highly detectable feature and Valorant Companion aims to be as invisible to Riot Games as possible and at the same time providing as many features as possible.
* Valorant Companion aims to be helpful but also non-disruptive. We want players to be able to have certain information but don't want them to be able to "cheat". Locking agents with inhumane speed just isn't fair in a gameplay perspective.

Following API-steps are required to achieve Recon Bolt's functionality:
1. Selecting a character: `https://glz-{region}-1.{shard}.a.pvp.net/pregame/v1/matches/{matchId}/select/{agentId}`
2. Then locking the character: `https://glz-{region}-1.{shard}.a.pvp.net/pregame/v1/matches/{matchId}/lock/{agentId}`

Please overthink using tools like Recon Bolt. Not just is there a high chance of you losing all your skins, but also is it disruptive against players without such tools.
