### ISSUE TITLE
Could not load VALORANT match data

### ISSUE THREAD

**Issue by jiannystein** [RXJpaw/Valorant-Companion#6]
Since 48 hours ago, maybe longer, I was not able to fetch data from 2.9.1 and just tested rebuilding from 2.10.0 with the same issue. May I know if anyone else is facing the same issue?

**Comment by RXJpaw** [comment]
I have no issues at all, can you show me a screenshot of your Valorant Companion with the developer console open (CTRL + SHIFT + I) and the window stretched to the right?

**Comment by jiannystein** [comment]
![image](https://github.com/RXJpaw/Valorant-Companion/assets/41028418/da6c70e1-d87e-47bb-ab0e-50a98f399c62)

Thanks for the swift response!

If I can recall correctly the only thing different was I tried to launch the game from this app instead of opening the game as I would usually do, not sure if that broke anything but the new exe is cached with my accounts as well, should I try going somewhere and deleting some files so I can start fresh?

**Comment by RXJpaw** [comment]
This doesn't seem like one of the rare errors I already know of. Are you willing to provide a screen share via discord? If so, please email me your discord-username (`github@rxj.pw`). For privacy reasons we should not share this information in this issue.

I won't have time right now but will negotiate a suitable time for us to see further into this issue.

**Comment by jiannystein** [comment]
Sure will drop you an email and this is what I got when in game 
![image](https://github.com/RXJpaw/Valorant-Companion/assets/41028418/310da7aa-b454-44ce-9f48-791250bea3c6)

**Comment by RXJpaw** [comment]
Thank you for providing me with your discord-username and further logs! Looking into them, this seems to be an issue I already know of. Looks like the assets api I use for receiving Valorant assets returned unexpected data when requesting them on version change. I already attempted to fix this issue in 2.10.0 but as you can see this didn't really work. My [previous attempt to fix this issue](https://github.com/RXJpaw/Valorant-Companion/commit/a5dbd77) clearly needs more attention.

**Comment by RXJpaw** [comment]
Thank you for making time to address this issue in more detail through screen sharing.
Please feel free to report further encounters.

The bug mentioned in this issue was fixed with commit 29dcfae.
Have a nice day!
