### ISSUE TITLE
add support for outlaw gun in loadout stuff

### ISSUE THREAD

**Issue by TheKfcBandit** [RXJpaw/Valorant-Companion#8]
yes

**Comment by RXJpaw** [comment]
Sorry for my late response. I'm in fact done with migrating since Jan 10th [cb4f05be153f455ee7321d4853770ff5bba6b6e4]
Unfortunately I can't find time to push a new version at the moment.
Neither did I find time to respond to your issue.

I'll comment again when I'm finished pushing a version.

**Comment by RXJpaw** [comment]
I'm happy to announce Valorant Companion 2.10.0!
Since this version fixes some vulnerabilities, a new installation is mandatory.
